### ISSUE TITLE
Обозначение выбранного тега

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [mirea-ninja/rtu-mirea-mobile#159]
**Проблема**
Невозможно определить, по какому тегу настроен фильтр.

**Опишите решение, которое вы хотели бы**
Менять цвет заливки овала выбранного тега.

**Альтернатива/дополнение**
Отобразить выбранный тег как выбранный раздел (наравне с разделами «Новости», «Важное»).

**Comment by 0niel** [comment]
Реализовано в #320
