### ISSUE TITLE
Обрезанное изображение истории

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [mirea-ninja/rtu-mirea-mobile#197]
**Проблема**
При соотношении сторон экрана 4:3 в книжной и альбомной ориентации изображение истории видно не полностью.

**Воспроизведение ошибки**
1. Открыть историю на устройстве с соотношением сторон 4:3

**Ожидаемое поведение**
Целостное изображение независимо от соотношения сторон устройства.

**Скриншоты**

Книжная ориентация
![IMG_2670](https://user-images.githubusercontent.com/70258211/157298540-6c5b5748-8c58-4dc2-9e9d-6d1a2bb4536d.png)
![IMG_2671](https://user-images.githubusercontent.com/70258211/157298579-cd15a3ac-4e09-4811-9e8e-675a9b3d226e.png)

Альбомная ориентация
![IMG_2672](https://user-images.githubusercontent.com/70258211/157298598-92d33280-dd29-471c-b5e8-19a0b91dc82b.png)
![IMG_2673](https://user-images.githubusercontent.com/70258211/157298610-f8eb05a7-fd20-4676-87ae-5b4f30d6feed.png)

**Смартфон**
 - Девайс: iPad
 - OS: iPadOS 14.3

**Comment by 0niel** [comment]
В #316 сторис теперь имеет ограничения по соотношению сторон - строго 9:16
![image](https://github.com/mirea-ninja/rtu-mirea-mobile/assets/51058739/8a5bd744-9b3a-4a75-9416-12512fc85aed)
