### ISSUE TITLE
Небольшие исправления в UI

### ISSUE THREAD

**Issue by d3adwolf** [mirea-ninja/rtu-mirea-mobile#228]
**Введение:**
В целом я всем доволен и ка#их-то багов в последние полгода я не наблюдал, но я имею немного перфекционизма в своей душе, поэтому хочу внести два предложения касательно UI и иконки приложения.
#
**1. Иконка приложения:**
Мне кажется на iOS/iPadOS/MacOS иконка приложения, точнее сам логотип довольно мелковат, если сравнивать с остальными иконками/логотипами в системе, ниже приложу скриншот с ноутбука и телефона, думаю заметно насколько логотип Ninja Mirea мелковат по сравнению с другими приложениями.

![alt text](https://i.imgur.com/Q5dU1C7.png)
<img src="https://i.imgur.com/AFZ9g91.jpg" width="450">

**2. Подровнять элементы UI:**
Не буду тут сильно расписывать, просто гляньте скриншот ниже, нужно эти кружочки (кол-во пар) опустить чуть-чуть пониже, так будет смотреться интерфейс поприятнее.

![alt text](https://i.imgur.com/5Uq410J.png)

**3. Переименовать приложение:**
Мне кажется нужно чуть-чуть подумать над названием, среди остальных приложение название "Mirea App" выглядит, будто приложение в бета-версии. 😃 Мне кажется можно попробовать, что-то по типу: MIREA, МИРЭА, NINJA MIREA, лично я за MIREA просто.
#
**К слову:**
Увидел pull-request https://github.com/mirea-ninja/rtu-mirea-mobile/pull/100 - лично мне идея крайне понравилась, лично я такой бы фигней пользовался всегда, непонятно только, почему вы её ещё не добавили. 🧐

**Comment by 0niel** [comment]
Привет! Спасибо за предложения. Если коротко - в ближайшие 2 месяца UI/UX приложения будет полностью переделан в лучшую сторону, а также будет опубликовано глобальное руководство по стилю с компонентам в Figma для внешних разработчиков. Сейчас мы всё готовим для этого. Данное крупное обновление связано с тем, что мы получили (почти) финансирование от университета, так как выиграли Акселератор 3.0. В связи с этим, иконка приложения и название будет изменено в сторону чего-то более мирэашного.

Как-то так получилось, что PR #100 отложили в долгий ящик из-за многих технических недостатков этого решения (например, локальное хранение заметок приводит к тому, что они пропадают после обновления), а полноценно допиливать эту систему мы не стали в пользу более приоритетных задач. Заметки обязательно будут реализованы в следующем обновлении, которое выйдет как версия 2.0.
