### ISSUE TITLE
Ещё один недочет в UI

### ISSUE THREAD

**Issue by d3adwolf** [mirea-ninja/rtu-mirea-mobile#229]
**Введение в проблему:**
Выбрана неделя с 25 апреля по 1 мая и визуализация недели обрывается перед воскресеньем, как-то не очень. Надо либо число следующего месяца добавить, либо как-то это дело переиграть.
<br>

<img src="https://i.imgur.com/Hbl9yIB.png" width="300">

**Смартфон:**
 - Девайс: iPhone XS Max (а надо говорить, что у меня 512Гб памяти?)
 - OS: 15.4.1
 - Версия: 1.2.1

**Comment by Dragonprod** [comment]
Спасибо за фидбек, об этом известно. В новой версии UI/UX все недочеты будут исправлены.
