### ISSUE TITLE
Неправильный порядок семестров в зачетной книжке

### ISSUE THREAD

**Issue by d3adwolf** [mirea-ninja/rtu-mirea-mobile#230]
**Введение в проблему:**
Зашёл в аккаунт приложения через личный кабинет МИРЭА, открыл зачетную книжку, а там вверху семестры перепутаны, тип сначала третий, потом первый и уже потом второй, весело, однако.
<br>

<img src="https://i.imgur.com/CKSbqxn.png" width="300">

**Смартфон:**
 - Девайс: iPhone XS Max
 - OS: 15.4.1
 - Версия: 1.2.1

**Comment by Dragonprod** [comment]
Спасибо за фидбек, об этом известно. В новой версии приложения все недочеты UI/UX  будут исправлены.

**Comment by ValeryVerkhoturov** [comment]
> Спасибо за фидбек, об этом известно. В новой версии приложения все недочеты UI/UX будут исправлены. 

Думаю, что было бы лучше оставить issue открытой, закрыть по факту устранения.

То же относится к #229.

**Comment by d3adwolf** [comment]
> 

И к #228
