### ISSUE TITLE
Лабы в расписании

### ISSUE THREAD

**Issue by RuFuZZZTheGreat** [mirea-ninja/rtu-mirea-mobile#243]
В расписании группы РССО-01-20(возможно, в других группах тоже) лабы на 3,5,7,... неделях неправильно показываются. На одной паре подгруппы, на другой название предмета. В общем, лабораторные предметы показываются на нескольких парах, а не на одной

**Comment by Dragonprod** [comment]
Привет, спасибо за фид бек. Взяли в работу.

**Comment by 0niel** [comment]
Спасибо. Выдача пустых подгрупп исправлена, но в расписании есть ошибки. Тут две пары в одно время. Я никак не могу это интерпретировать, поэтому ждём фикса со стороны УМУ
![image](https://user-images.githubusercontent.com/51058739/187988133-51b011ce-c1f0-44d8-80df-ff29e5c2b8bd.png)

**Comment by RuFuZZZTheGreat** [comment]
Это нормально, что тут две пары в одно время. Разные подгруппы на разные
предметы в одно время идут и через две недели эти подгруппы меняются
предметами. В целом есть вариант реализации выбора подгруппы на лабы в
приложении, но это уже ваше желание. Хотя, думаю, это можно рассмотреть,
как предложение новой фичи)

чт, 1 сент. 2022 г. в 21:38, Sergey Dmitriev ***@***.***>:
