### ISSUE TITLE
Не отображаются некоторые оценки, если они выставлены на одну дату

### ISSUE THREAD

**Issue by ruscalworld** [mirea-ninja/rtu-mirea-mobile#297]
**Описание ошибки**
В первом семестре, видимо, преподаватель допустил ошибку, и по итогу оценки за зачёт и экзамен по физике стоят на одну дату (которая сама по себе неправильная, но не думаю, что это имеет значение). При таком раскладе в зачётной книжные отображается только одна оценка.

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Получите зачёт по физике и сдайте экзамен
2. Как-то допустите ситцацию, при которой преподаватель поставит оценки на одну дату
3. Перейдите во вкладку "Зачётная книжка" в приложении
4. Смотрите ошибку

**Ожидаемое поведение**
Должны отображаться обе оценки: за зачёт и за экзамен.

**Скриншоты**
![Screenshot_20230227-081221_Chrome.png](https://user-images.githubusercontent.com/60034902/221479717-5e7a47ba-069c-4201-bd83-250d8629b782.png)

![Screenshot_20230227-081423.png](https://user-images.githubusercontent.com/60034902/221479821-33379af6-23df-4797-be61-ca1856cf9d5c.png)

**Смартфон:**
 - Девайс: Samsung Galaxy A12 SM-A125F
 - OS: Android 12
 - Браузер: Google Chrome
 - Версия: 110.0.5481.154

**Comment by lokot0k** [comment]
Столкнулся с такой же ошибкой. Оценки по физике неправильно отображаются скорее всего из-за проблем хранения дисциплин в мапе(зачет и экзамен имеют одно и то же имя). В мапу оценок складывается что-то одно, либо экзамен, либо зачет. Баг здесь: https://github.com/mirea-ninja/rtu-mirea-mobile/blob/4f2c1e00cd28b351a50418af609d9c502fbc0513/lib/data/datasources/user_remote.dart#L148-L158
Необходимо добавить обработку случая, когда у дисциплин одинаковое имя

**Comment by 0niel** [comment]
@ruscalworld, спасибо за описание проблемы и предложенное воспроизведение, а также @lokot0k  за указание на возможное место бага в коде.

Проблема действительно связана с тем, что при попытке получить оценки для предметов с одинаковым именем, мы учитываем только первый результат.
