### ISSUE TITLE
Авторизация лкс в фоновом режиме

### ISSUE THREAD

**Issue by lokot0k** [mirea-ninja/rtu-mirea-mobile#299]
**Проблема**
Навязчивость самопроизвольного всплывающего окошка авторизации при старте приложения

**Решение**
Сохранять логин и пароль в внешнем хранилище, или внутреннем (может даже кэше), если такое позволяет функционал. Авторизовывать пользователя с помощью них в фоновом режиме при запуске приложения

**Альтернативное решение**
Если нет возможности реализовать предыдущее решение, то можно запрашивать авторизацию по нажатию на кнопку профиля в нижней панели приложения. 

**Дополнительный текст**
Запрашиваю такую фичу по причинам удобства. Раздражает при очередном запуске видеть это окно

**Comment by 0niel** [comment]
@lokot0k, как часто у вас сбрасывается сессия (требуется повторный вход)?

**Comment by 0niel** [comment]
> @0niel, по разному, но раз в день точно сбрасывается. Иногда может потребоваться всего несколько часов для новой авторизации

Используете ли вы для авторизации где-либо помимо auth-app.mirea.ru еще и lks.mirea.ninja? Например, сейчас в реализации клиента прописал именно этот домен (https://github.com/mirea-ninja/rtu-mirea-mobile/blob/358a7c4d6407c93069bf65c95fed5be55cc0ee67/lib/common/oauth.dart#L9)

**Comment by lokot0k** [comment]
Нет, не использую

**Comment by lokot0k** [comment]
Сейчас поставлю, через пару дней или по выявлению проблемы отпишу

**Comment by lokot0k** [comment]
Насколько я могу судить, проблема в этом билде решена. По крайней мере, сессия ни разу не истекла за эти 3 дня. Спасибо!

**Comment by 0niel** [comment]
> Насколько я могу судить, проблема в этом билде решена. По крайней мере, сессия ни разу не истекла за эти 3 дня. Спасибо!

Отлично! Будем считать, что проблема решена
