### ISSUE TITLE
Неправильное количество пар

### ISSUE THREAD

**Issue by ruscalworld** [mirea-ninja/rtu-mirea-mobile#317]
**Описание ошибки**
После обновления серверной части занятия у двух разных подгрупп в одно время считаются как два разных занятия, что несколько вводит в заблуждение.

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейти в "Расписание".
2. Открыть день, когда по расписанию есть деление на подгруппы.
3. Смотрите ошибку.

**Ожидаемое поведение**
Занятия разных подгрупп в одно время считаются как одно занятие, как и раньше. Считаю, что в примере со скриншота должно отображаться две точки под датой вместо трёх.

**Скриншоты**
![Screenshot_20230523-104337.png](https://github.com/mirea-ninja/rtu-mirea-mobile/assets/60034902/13438a30-1321-43d5-8d29-3c72e68faa1b)

**Смартфон:**
 - Девайс: Samsung Galaxy A12 SM-A125F
 - OS: Android 12
 - Браузер Google Chrome
 - Версия 113.0.5672.131

**Дополнительно**
Не уверен, может это и ожидаемое поведение, а я просто привык к старому варианту, но он всё же кажется мне более логичным.

**Comment by 0niel** [comment]
Исправлено в #318
