### ISSUE TITLE
Поле ввода группы перекрывает стандартный интерфейс iPadOS

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [mirea-ninja/rtu-mirea-mobile#96]
**Описание ошибки**
В альбомной ориентации iPadOS время, дата накладываются на поле ввода группы

**Воспроизведение ошибки**
Шаги воспроизведения:
1. Перейдите в окно ввода группы
2. Нажмите на поле ввода
3. Смотрите ошибку

**Ожидаемое поведение**
Поле ввода располагается ниже времени и даты.

**Скриншоты**
![F6D4FC32-B7F1-412E-ADF7-12D915F1EDE0](https://user-images.githubusercontent.com/70258211/132831292-280d56a9-dd95-4284-a112-5ec8be843dc7.png)

**Смартфон:**
 - Девайс: iPad
 - OC: iPadOS 14.3

**Comment by 0niel** [comment]
Страница выбора группы полностью переработана в #270. Подобной проблемы больше не наблюдаю
